import React, { useState } from 'react';
import { useSelector } from 'react-redux';
import { selectApiKey, selectIsAiConfigured } from '../../features/ai/aiSlice';
import { aiService } from '../../services/aiService';
import './AISummary.css';

function AISummary({ policy }) {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [showSummary, setShowSummary] = useState(false);
  
  const apiKey = useSelector(selectApiKey);
  const isAIConfigured = useSelector(selectIsAiConfigured);

  const generateSummary = async () => {
    if (!isAIConfigured) {
      setError('Please configure your AI settings first');
      return;
    }

    setIsLoading(true);
    setError('');
    
    try {
      const generatedSummary = await aiService.generatePolicySummary(apiKey, policy);
      setSummary(generatedSummary);
      setShowSummary(true);
    } catch (err) {
      setError(err.message || 'Failed to generate summary');
    } finally {
      setIsLoading(false);
    }
  };

  if (!isAIConfigured) {
    return (
      <div className="ai-summary-container">
        <div className="ai-feature-disabled">
          <p>🤖 AI features are not configured. Please set up your API key in the settings.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="ai-summary-container">
      {!showSummary && (
        <button 
          className="generate-summary-button"
          onClick={generateSummary}
          disabled={isLoading}
        >
          {isLoading ? 'Generating Summary...' : '🤖 Generate AI Summary'}
        </button>
      )}

      {error && (
        <div className="ai-error">
          <p>❌ {error}</p>
        </div>
      )}

      {showSummary && summary && (
        <div className="ai-summary">
          <div className="ai-summary-header">
            <h3>🤖 AI Summary</h3>
            <button 
              className="regenerate-button"
              onClick={generateSummary}
              disabled={isLoading}
              title="Regenerate summary"
            >
              🔄
            </button>
          </div>
          <div className="ai-summary-content">
            {summary}
          </div>
          <div className="ai-summary-footer">
            Generated by AI • Results may vary
          </div>
        </div>
      )}
    </div>
  );
}

export default AISummary;